syntax = 'Lua51'
space_after_function_names = "Never"
indent_type = "Spaces"
indent_width = 4
column_width = 100
line_endings = "Unix"
quote_style = "AutoPreferDouble"
call_parentheses = "Always"
collapse_simple_statement = "Never"

[sort_requires]
enabled = false
