import = [
  "/Users/joshmedeski/.config/alacritty/catppuccin/catppuccin-mocha.toml",
]
live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 20.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Heavy"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Heavy Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Medium Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[[keyboard.bindings]]
chars = "\u0002 "
key = "C"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002\""
key = "E"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002%"
key = "E"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = """
:Grep
"""
key = "F"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002[/"
key = "F"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002g"
key = "G"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002G"
key = "G"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002T"
key = "J"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002T"
key = "K"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002L"
key = "L"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002u"
key = "O"
mods = "Command"

[[keyboard.bindings]]
chars = """
:GoToFile
"""
key = "P"
mods = "Command"

[[keyboard.bindings]]
chars = """
:GoToCommand
"""
key = "P"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = """
:q
"""
key = "Q"
mods = "Command"

[[keyboard.bindings]]
chars = """
\u001B:w
"""
key = "S"
mods = "Command"

[[keyboard.bindings]]
chars = """
\u001B:wq
"""
key = "S"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002c"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002]"
key = "V"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002P"
key = "T"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002x"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002z"
key = "Z"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002n"
key = "Tab"
mods = "Control"

# TODO: fix "Grave"
# [[keyboard.bindings]]
# chars = "\u0002p"
# key = "Grave"
# mods = "Control"

[[keyboard.bindings]]
chars = "\u0002,"
key = "Comma"
mods = "Command"

[[keyboard.bindings]]
chars = """
:ZenMode
"""
key = "Period"
mods = "Command"

[[keyboard.bindings]]
chars = "\u000F"
key = "LBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002p"
key = "LBracket"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\t"
key = "RBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002n"
key = "RBracket"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002:"
key = "Semicolon"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00021"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00022"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00023"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00024"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00025"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00026"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00027"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00028"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00029"
key = "Key9"
mods = "Command"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.9

[window.padding]
x = 25
y = 20
